force-app/main/default/objects/FAQ__c/FAQ__c.object-meta.xml
<CustomObject>
    <label>FAQ</label>
    <nameField>
        <displayFormat>FAQ-{0000}</displayFormat>
        <label>FAQ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FAQs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FAQ__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>Answer to frequently asked question.</description>
    <inlineHelpText>Answer to frequently asked question.</inlineHelpText>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FAQ__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Frequently asked question.</description>
    <inlineHelpText>Frequently asked question.</inlineHelpText>
    <label>Question</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/FAQTriggerHandler.cls
public class FAQTriggerHandler {
    public static List<FAQ__c> checkExistingFAQs(List<FAQ__c> newFAQs) {
        Set<String> newFAQSet = new Set<String>();
        for(FAQ__c newFAQ : newFAQs) {
            if(newFAQ.Question__c != null && newFAQ.Answer__c != null ) {
                newFAQSet.add(newFAQ.Question__c);
            }
        }
        List<FAQ__c> existingFAQList = new List<FAQ__c>();
        for(FAQ__c existingFAQ: [SELECT Question__c, Answer__c FROM FAQ__c]) {
            existingFAQList.add(existingFAQ);
        }
        Integer i = 0;
        for(FAQ__c newFAQ: newFAQs) {
            if(newFAQ.Question__c == existingFAQList[i].Question__c) {
                newFAQ.addError('ERROR: This question already exists as an FAQ.');
            }
            i++;
        }
        return newFAQs;
    }
}