force-app/main/default/objects/FAQ__c/FAQ__c.object-meta.xml
<CustomObject>
    <label>FAQ</label>
    <nameField>
        <displayFormat>FAQ-{0000}</displayFormat>
        <label>FAQ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FAQs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FAQ__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>Answer to frequently asked question.</description>
    <inlineHelpText>Answer to frequently asked question.</inlineHelpText>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FAQ__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Frequently asked question.</description>
    <inlineHelpText>Frequently asked question.</inlineHelpText>
    <label>Question</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/FAQController.cls
public class FAQController {    
    public String searchInput {get;set;}
    public List<FAQ__c> matchingQuestion{get;set;}
    public String errorMessage {get;set;}
    public List<FAQ__c> FAQList = new List<FAQ__c>();

    public void getQandA() {
        try {
            if (String.isEmpty(this.searchInput)) {
                FAQList = [SELECT Question__c, Answer__c FROM FAQ__c];
            }
            else {
                FAQList = [SELECT Question__c, Answer__c FROM FAQ__c WHERE Question__c LIKE :searchInput];
            }
        }
        catch (Exception e){
            this.errorMessage = 'Please enter a question in the text box before clicking the serach button.';
            this.matchingQuestion = new List<FAQ__c>();
        }        
    }
 
}