force-app/main/default/objects/Potion__c/Potion__c.object-meta.xml
<CustomObject>
    <label>Potion</label>
    <nameField>
        <label>Potion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion_Review__c/Potion_Review__c.object-meta.xml
<CustomObject>
    
    <label>Potion Review</label>
    <nameField>
        <displayFormat>RID-{0000}</displayFormat>
        <label>Potion Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potion Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion_Review__c/fields/Potion_Type__c.field-meta.xml
<CustomField>
    <fullName>Potion_Type__c</fullName>
    <label>Potion Type</label>
    <referenceTo>Potion__c</referenceTo>
    <relationshipLabel>Potion Reviews</relationshipLabel>
    <relationshipName>Potion_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Potion_Review__c/fields/Review_Message__c.field-meta.xml
<CustomField>
    <fullName>Review_Message__c</fullName>
    <label>Review Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Potion_Review__c/fields/Review_Rating__c.field-meta.xml
<CustomField>
    <fullName>Review_Rating__c</fullName>
    <inlineHelpText>How would you rate this product? Rank 0-5 with 0 being the worst and 5 being the best.</inlineHelpText>
    <label>Review Rating</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Potion_Review__c/fields/Reviewer_Name__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Name__c</fullName>
    <label>Reviewer Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReviewPageController.cls
public class ReviewPageController {
    
    // create a new review object to store new details to submit a new review from the page
    public Potion_Review__c newReview
    {
        get
        {
            if(newReview == null)
            {
                newReview = new Potion_Review__c();
            }
            return newReview;
        }
        set;
    }
    
    
    // instantiation of a set controller for standard list controller
    public ApexPages.StandardSetController setController
    {
        get
        {
            if(setController == null)
            {
                setController = new ApexPages.StandardSetController(Database.getQueryLocator(
                		[SELECT Name, Potion_Type__c, Potion_Type__r.Name, Review_Message__c, Review_Rating__c, Reviewer_Name__c FROM Potion_Review__c]
                		));
            }
            return setController;
        }
        set;
    }

    // custom constructor for the controller to retrieve list of all Potion Review records
    // and setup the newReview object
    public ReviewPageController()
    {
        setController = new ApexPages.StandardSetController(Database.getQueryLocator(
                [SELECT Name, Potion_Type__c, Potion_Type__r.Name, Review_Message__c, Review_Rating__c, Reviewer_Name__c FROM Potion_Review__c]
                ));
        newReview = new Potion_Review__c();
    }
    
    
    // initialize setController and return a list of all potion review records
    public List<Potion_Review__c> getPotionReviews()
    {
        return(List<Potion_Review__c>) setController.getRecords();
    }
    
    // method to save a new record and is called from a button press on page
    // input fields on page provide details
    public PageReference saveReview()
    {
        insert newReview;
        PageReference pref = new ApexPages.StandardController(newReview).view();
		return pref;
    }
}