force-app/main/default/objects/Potion__c/Potion__c.object-meta.xml
<CustomObject>
    <label>Potion</label>
    <nameField>
        <label>Potion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion__c/fields/Base_Ingredient__c.field-meta.xml
<CustomField>
    <fullName>Base_Ingredient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Base Ingredient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Ingredient__c.Type_of_Ingredient__c</field>
            <operation>equals</operation>
            <value>Base</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ingredient__c</referenceTo>
    <relationshipLabel>Potions</relationshipLabel>
    <relationshipName>Potions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Potion__c/fields/Secondary_Ingredient__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Ingredient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Ingredient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Ingredient__c.Type_of_Ingredient__c</field>
            <operation>equals</operation>
            <value>Secondary</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type_of_Potion__c</field>
            <operation>equals</operation>
            <valueField>Ingredient__c.Available_Potion__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ingredient__c</referenceTo>
    <relationshipLabel>Potions (Secondary Ingredient)</relationshipLabel>
    <relationshipName>Potions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Potion__c/fields/Type_of_Potion__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Potion__c</fullName>
    <label>Type of Potion</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Potion_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Potion_Order__c/Potion_Order__c.object-meta.xml
<CustomObject>
    <label>Potion Order</label>
    <nameField>
        <displayFormat>POI-{0000}</displayFormat>
        <label>Potion Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potion Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion_Order__c/fields/Number_of_Potions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Potions__c</fullName>
    <label>Number of Potions</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Potion_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Healing</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Speed</fullName>
    </customValue>
    <customValue>
        <fullName>Visions</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep</fullName>
    </customValue>
    <masterLabel>Potion Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CartPageExtensionTest.cls
@isTest
public with sharing class CartPageExtensionTest {
    
    @isTest
    public static void testInsert(){
        Potion__c pot = new Potion__c(
            Name = 'Potion of Healing',
            Type_of_Potion__c = 'Healing',
            Base_Ingredient__c = 'a005f000000wr0ZAAQ',
            Secondary_Ingredient__c = 'a005f000000wr0eAAA'
        );
        insert pot;

        PageReference pageRef = Page.CartPage;
        pageRef.getParameters().put('potId', pot.Id);
        Test.setCurrentPage(pageRef);

        Potion_Order__c potOrder = new Potion_Order__c();
        ApexPages.StandardController ssc = new ApexPages.StandardController(potOrder);

        CartPageExtension cpe = new CartPageExtension(ssc);
        potOrder.Number_of_Potions__c = 1;

        cpe.showPopup();

        List<Potion_Order__c> potOrders = [SELECT id from Potion_Order__c];
        System.assertEquals(1, potOrders.size());

        PageReference nePage = cpe.closePopup();

        Test.setCurrentPage(nePage);

        System.assertEquals(Page.PotionsPage.getUrl(), ApexPages.currentPage().getUrl());
    }
}