force-app/main/default/objects/Potion__c/Potion__c.object-meta.xml
<CustomObject>
    <label>Potion</label>
    <nameField>
        <label>Potion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Base_Ingredient__r.Ingredient_Price__c  +  Secondary_Ingredient__r.Ingredient_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Potion_Order__c/Potion_Order__c.object-meta.xml
<CustomObject>
    <label>Potion Order</label>
    <nameField>
        <displayFormat>POI-{0000}</displayFormat>
        <label>Potion Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potion Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion_Order__c/fields/Account_Purchasing__c.field-meta.xml
<CustomField>
    <fullName>Account_Purchasing__c</fullName>
    <label>Account Purchasing</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Potion Orders</relationshipLabel>
    <relationshipName>Potion_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Potion_Order__c/fields/Number_of_Potions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Potions__c</fullName>
    <label>Number of Potions</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Potion_Order__c/fields/Potion_Type__c.field-meta.xml
<CustomField>
    <fullName>Potion_Type__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Potion Type</label>
    <referenceTo>Potion__c</referenceTo>
    <relationshipLabel>Potion Orders</relationshipLabel>
    <relationshipName>Potion_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CartPageExtension.cls
public class CartPageExtension {
    
    public Potion__c potion {get; set;}
    public Decimal orderTotalPrice{get;set;}
    public boolean displayPopup {get;set;} 
    private final ApexPages.StandardController ctllr;

    public CartPageExtension(ApexPages.StandardController controller){
        // store controller locally for use when saving record
        ctllr = controller;

        // Get the potion id passed in via the url, query for that potion,
        // then assign to local property.
        String potionId = ApexPages.currentPage().getParameters().get('potId');
        if (potionId == null) {
            potionId = 'a015f000003jCdX';
        }
        string query = 'SELECT Id, Name, Total_Price__c ' +
        'FROM Potion__c WHERE Id = \'' + potionID + '\'';
        List<Potion__c> potions = Database.query(
            query
        );
        potion = potions[0];
    }
    
    public Pagereference closePopup() {
        // Redirect user to Potions page
        return Page.PotionsPage;
    } 

    public void showPopup() {
        try{ 
            // Get record from controller and assign the potion passed in from URL 
            // and hard code the purchasing account then insert.
            Potion_Order__c potOrder = (Potion_Order__c)ctllr.getRecord();
            potOrder.Potion_Type__c = potion.Id;
            potOrder.Account_Purchasing__c = '0015f000002GbCvAAK';
            insert potOrder;

            // If no errors then display pop up and calculate total price
            // wanted to use object field but did not work as expected
            displayPopup = true;
            orderTotalPrice = potion.Total_Price__c * potOrder.Number_of_Potions__c;
        } catch(Exception e) {
            // Automatic error handling and placement
        }
    }
}