force-app/main/default/objects/Ingredient__c/Ingredient__c.object-meta.xml
<CustomObject>
    <label>Ingredient</label>
    <nameField>
        <label>Ingredient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ingredients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion__c/Potion__c.object-meta.xml
<CustomObject>
    <label>Potion</label>
    <nameField>
        <label>Potion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion__c/fields/Base_Ingredient__c.field-meta.xml
<CustomField>
    <fullName>Base_Ingredient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Base Ingredient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Ingredient__c.Type_of_Ingredient__c</field>
            <operation>equals</operation>
            <value>Base</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ingredient__c</referenceTo>
    <relationshipLabel>Potions</relationshipLabel>
    <relationshipName>Potions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Potion__c/fields/Secondary_Ingredient__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Ingredient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Ingredient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Ingredient__c.Type_of_Ingredient__c</field>
            <operation>equals</operation>
            <value>Secondary</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type_of_Potion__c</field>
            <operation>equals</operation>
            <valueField>Ingredient__c.Available_Potion__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ingredient__c</referenceTo>
    <relationshipLabel>Potions (Secondary Ingredient)</relationshipLabel>
    <relationshipName>Potions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Potion__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Base_Ingredient__r.Ingredient_Price__c  +  Secondary_Ingredient__r.Ingredient_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Potion__c/fields/Type_of_Potion__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Potion__c</fullName>
    <label>Type of Potion</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Potion_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Potion_Order__c/Potion_Order__c.object-meta.xml
<CustomObject>
    <label>Potion Order</label>
    <nameField>
        <displayFormat>POI-{0000}</displayFormat>
        <label>Potion Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potion Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Potion_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Healing</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Speed</fullName>
    </customValue>
    <customValue>
        <fullName>Visions</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep</fullName>
    </customValue>
    <masterLabel>Potion Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PotionCatalogueController.cls
public class PotionCatalogueController {
    @AuraEnabled
    public static List<Potion__c> fetchPotionList(String filter){
        
        if (filter != null) {
            if (filter == 'See All') {
                return [SELECT Id, Name, Total_Price__c, Type_of_Potion__c, Base_Ingredient__r.Name,CreatedDate, Secondary_Ingredient__r.Name FROM Potion__c];
            }    
            return [SELECT Id, Name, Total_Price__c, Type_of_Potion__c, Base_Ingredient__r.Name, CreatedDate, Secondary_Ingredient__r.Name FROM Potion__c WHERE Type_of_Potion__c = : filter ];
        } 
        
     return  [SELECT Id, Name, Total_Price__c, Type_of_Potion__c, Base_Ingredient__r.Name,CreatedDate, Secondary_Ingredient__r.Name FROM Potion__c]; 
        
    }
    
    @AuraEnabled
    public static Potion_Order__c saveOrder(Potion_Order__c order) {
        upsert order;
        return order;
    }
    
    @AuraEnabled
    
    public static List<String> getOptions(){
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Potion__c.Type_of_Potion__c.getDescribe();
        List<Schema.PicklistEntry> pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pList) {
            options.add(p.getLabel());
        }
        return options;
    }
   
    /*
    // Grabbing potion instance
    @AuraEnabled
    public static Potion__c getPotionInstance(String i) {
        // returing object
        return [SELECT Id, Name, Type_of_Potion__c, Base_Ingredient__r.Name, Secondary_Ingredient__r.Name FROM Potion__c WHERE Id = :i];
    }

*/
}