force-app/main/default/objects/Ingredient__c/Ingredient__c.object-meta.xml
<CustomObject>
    <label>Ingredient</label>
    <nameField>
        <label>Ingredient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ingredients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Ingredient__c/fields/Available_Potion__c.field-meta.xml
<CustomField>
    <fullName>Available_Potion__c</fullName>
    <inlineHelpText>Select the potion type that this ingredient can be used for</inlineHelpText>
    <label>Available Potion</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type_of_Ingredient__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Potion_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ingredient__c/fields/Ingredient_Price__c.field-meta.xml
<CustomField>
    <fullName>Ingredient_Price__c</fullName>
    <label>Ingredient Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ingredient__c/fields/Type_of_Ingredient__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Ingredient__c</fullName>
    <label>Type of Ingredient</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Base</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Potion__c/Potion__c.object-meta.xml
<CustomObject>
    <label>Potion</label>
    <nameField>
        <label>Potion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Potions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion__c/fields/Base_Ingredient__c.field-meta.xml
<CustomField>
    <fullName>Base_Ingredient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Base Ingredient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Ingredient__c.Type_of_Ingredient__c</field>
            <operation>equals</operation>
            <value>Base</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ingredient__c</referenceTo>
    <relationshipLabel>Potions</relationshipLabel>
    <relationshipName>Potions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Potion__c/fields/Secondary_Ingredient__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Ingredient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Ingredient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Ingredient__c.Type_of_Ingredient__c</field>
            <operation>equals</operation>
            <value>Secondary</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type_of_Potion__c</field>
            <operation>equals</operation>
            <valueField>Ingredient__c.Available_Potion__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Ingredient__c</referenceTo>
    <relationshipLabel>Potions (Secondary Ingredient)</relationshipLabel>
    <relationshipName>Potions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Potion__c/fields/Type_of_Potion__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Potion__c</fullName>
    <label>Type of Potion</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Potion_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Potion_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Healing</fullName>
    </customValue>
    <customValue>
        <fullName>Poison</fullName>
    </customValue>
    <customValue>
        <fullName>Speed</fullName>
    </customValue>
    <customValue>
        <fullName>Visions</fullName>
    </customValue>
    <customValue>
        <fullName>Sleep</fullName>
    </customValue>
    <masterLabel>Potion Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PotionCatalogueControllerTest.cls
@isTest
public class PotionCatalogueControllerTest {
	@TestSetup
    static void makeData() {
        //create single base Ingredient
        Ingredient__c myIngr = new Ingredient__c(Name = 'TheIngredient', Ingredient_Price__c = 0.6, Type_of_Ingredient__c = 'Base'); 
        insert myIngr;

        //create a secondary Ingredient
        Ingredient__c secIngr = new Ingredient__c(Name='ingr2', Ingredient_Price__c = 0.3, Type_of_Ingredient__c= 'Secondary', Available_Potion__c='Healing');
        insert secIngr;

        List<Potion__C> testPotions = new List<Potion__c>();
            for (Integer i = 0; i < 120; i++) {
                testPotions.add(new Potion__c(name = 'Pot' + i,
                Base_Ingredient__c = myIngr.Id, Type_of_Potion__c = 'Healing'));
            }
            insert testPotions;
    }

    @isTest public static void testGettingPotions() {
        //see if this method is returning the 100 records we have created earlier
       
        
        //getting the single secondary Ingredient from the Setup
        Ingredient__c mySec = [SELECT id, name, Ingredient_Price__c, Type_of_Ingredient__c, Available_Potion__c FROM Ingredient__c WHERE Available_Potion__c = 'Healing'][0];
        Ingredient__c myBase = [SELECT id, name, Ingredient_Price__c, Type_of_Ingredient__c FROM Ingredient__c WHERE Type_of_Ingredient__c = 'Base'][0];

        Potion__c myOne = new Potion__c(Name='myPoo', Base_Ingredient__c = myBase.Id, Secondary_Ingredient__c = mySec.Id, Type_of_Potion__c = 'Healing');
        insert myOne;

        List<Potion__c> myList = PotionCatalogueController.fetchPotionList();

        Test.startTest();  
        System.assertEquals(121, myList.size());
        Test.stopTest();
    }

}