force-app/main/default/objects/Potion_Review__c/Potion_Review__c.object-meta.xml
<CustomObject>
    
    <label>Potion Review</label>
    <nameField>
        <displayFormat>RID-{0000}</displayFormat>
        <label>Potion Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potion Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion_Review__c/fields/Review_Message__c.field-meta.xml
<CustomField>
    <fullName>Review_Message__c</fullName>
    <label>Review Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Potion_Review__c/fields/Review_Rating__c.field-meta.xml
<CustomField>
    <fullName>Review_Rating__c</fullName>
    <inlineHelpText>How would you rate this product? Rank 0-5 with 0 being the worst and 5 being the best.</inlineHelpText>
    <label>Review Rating</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReviewControllerExtension.cls
public class ReviewControllerExtension {
    public List<Potion_Review__c> prList=new list<Potion_Review__c>();
    
    
    //constructor:
    public ReviewControllerExtension(ReviewPageController recon){
        prList= new list<Potion_Review__C>([SELECT Review_Message__c FROM Potion_Review__C WHERE Review_Rating__c>=4 ORDER BY CreatedDate LIMIT 5]);      
    }
    
}

//[SELECT Review_Message__c FROM Potion_Review__C WHERE Review_Rating__c>=4 LIMIT 5];