force-app/main/default/objects/Potion_Review__c/Potion_Review__c.object-meta.xml
<CustomObject>
    
    <label>Potion Review</label>
    <nameField>
        <displayFormat>RID-{0000}</displayFormat>
        <label>Potion Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potion Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Potion_Review__c/fields/Potion_Type__c.field-meta.xml
<CustomField>
    <fullName>Potion_Type__c</fullName>
    <label>Potion Type</label>
    <referenceTo>Potion__c</referenceTo>
    <relationshipLabel>Potion Reviews</relationshipLabel>
    <relationshipName>Potion_Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Potion_Review__c/fields/Review_Message__c.field-meta.xml
<CustomField>
    <fullName>Review_Message__c</fullName>
    <label>Review Message</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Potion_Review__c/fields/Review_Rating__c.field-meta.xml
<CustomField>
    <fullName>Review_Rating__c</fullName>
    <inlineHelpText>How would you rate this product? Rank 0-5 with 0 being the worst and 5 being the best.</inlineHelpText>
    <label>Review Rating</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Potion_Review__c/fields/Reviewer_Name__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Name__c</fullName>
    <label>Reviewer Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DisplayReviewsController.cls
public class DisplayReviewsController {
	@AuraEnabled
    public static List<Potion_Review__c> getReviews() {
        return [SELECT Id, Review_Message__c, Reviewer_Name__c, Review_Rating__c, Potion_Type__c FROM Potion_Review__c];
    }
    
    @AuraEnabled
    public static List<Potion_Review__c> filterByPotion(Id filter) {
        return [SELECT Id, Review_Message__c, Reviewer_Name__c, Review_Rating__c, Potion_Type__c 
                FROM Potion_Review__c WHERE Potion_Type__c =: filter];
    }
    
    @AuraEnabled
    public static List<Potion_Review__c> filterByReviewer(String filter) {
        return [SELECT Id, Review_Message__c, Reviewer_Name__c, Review_Rating__c, Potion_Type__c 
                FROM Potion_Review__c WHERE Reviewer_Name__c =: filter];
    }
    
    @AuraEnabled
    public static List<Potion_Review__c> filterByRating(Integer filter) {
        return [SELECT Id, Review_Message__c, Reviewer_Name__c, Review_Rating__c, Potion_Type__c 
                FROM Potion_Review__c WHERE Review_Rating__c =: filter];
    }
}